# Black Friday Project

Import Black Friday Dataset

In [1]:
import pandas as pd

bftrain = pd.read_csv('train.csv')
bftest = pd.read_csv('test.csv')

In [2]:
bftrain

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969
5,1000003,P00193542,M,26-35,15,A,3,0,1,2.0,NaN,15227
6,1000004,P00184942,M,46-50,7,B,2,1,1,8.0,17.0,19215
7,1000004,P00346142,M,46-50,7,B,2,1,1,15.0,NaN,15854
8,1000004,P0097242,M,46-50,7,B,2,1,1,16.0,NaN,15686
9,1000005,P00274942,M,26-35,20,A,1,1,8,NaN,NaN,7871
10,1000005,P00251242,M,26-35,20,A,1,1,5,11.0,NaN,5254
11,1000005,P00014542,M,26-35,20,A,1,1,8,NaN,NaN,3957
12,1000005,P00031342,M,26-35,20,A,1,1,8,NaN,NaN,6073
13,1000005,P00145042,M,26-35,20,A,1,1,1,2.0,5.0,15665
14,1000006,P00231342,F,51-55,9,A,1,0,5,8.0,14.0,5378
15,1000006,P00190242,F,51-55,9,A,1,0,4,5.0,NaN,2079
16,1000006,P0096642,F,51-55,9,A,1,0,2,3.0,4.0,13055
17,1000006,P00058442,F,51-55,9,A,1,0,5,14.0,NaN,8851
18,1000007,P00036842,M,36-45,1,B,1,1,1,14.0,16.0,11788
19,1000008,P00249542,M,26-35,12,C,4+,1,1,5.0,15.0,19614
20,1000008,P00220442,M,26-35,12,C,4+,1,5,14.0,NaN,8584
21,1000008,P00156442,M,26-35,12,C,4+,1,8,NaN,NaN,9872
22,1000008,P00213742,M,26-35,12,C,4+,1,8,NaN,NaN,9743
23,1000008,P00214442,M,26-35,12,C,4+,1,8,NaN,NaN,5982
24,1000008,P00303442,M,26-35,12,C,4+,1,1,8.0,14.0,11927
25,1000009,P00135742,M,26-35,17,C,0,0,6,8.0,NaN,16662
26,1000009,P00039942,M,26-35,17,C,0,0,8,NaN,NaN,5887
27,1000009,P00161442,M,26-35,17,C,0,0,5,14.0,NaN,6973
28,1000009,P00078742,M,26-35,17,C,0,0,5,8.0,14.0,5391
29,1000010,P00085942,F,36-45,1,B,4+,1,2,4.0,8.0,16352
...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,F,36-45,1,C,2,1,20,NaN,NaN,596
550039,1005996,P00371644,F,26-35,0,B,1,1,20,NaN,NaN,595
550040,1005997,P00370853,F,26-35,7,A,3,0,19,NaN,NaN,26
550041,1006000,P00371644,M,46-50,17,B,2,1,20,NaN,NaN,488
550042,1006002,P00371644,M,51-55,0,C,1,1,20,NaN,NaN,243
550043,1006003,P00370293,F,46-50,17,C,1,0,19,NaN,NaN,48
550044,1006004,P00370853,F,26-35,15,C,2,0,19,NaN,NaN,62
550045,1006005,P00371644,F,26-35,5,C,2,1,20,NaN,NaN,252
550046,1006006,P00375436,F,0-17,0,C,1,0,20,NaN,NaN,236
550047,1006009,P00372445,F,26-35,12,C,3,0,20,NaN,NaN,244
550048,1006010,P00371644,M,36-45,0,C,1,0,20,NaN,NaN,591
550049,1006011,P00375436,M,36-45,15,C,3,0,20,NaN,NaN,473
550050,1006012,P00371644,M,36-45,15,C,4+,1,20,NaN,NaN,368
550051,1006013,P00375436,F,26-35,20,C,3,0,20,NaN,NaN,489
550052,1006016,P00375436,M,46-50,1,B,1,1,20,NaN,NaN,239
550053,1006017,P00371644,F,36-45,7,B,1,0,20,NaN,NaN,371
550054,1006018,P00370293,M,36-45,1,C,3,0,19,NaN,NaN,60
550055,1006019,P00372445,M,26-35,0,A,4+,0,20,NaN,NaN,238
550056,1006022,P00375436,M,26-35,17,C,4+,0,20,NaN,NaN,254
550057,1006023,P00370853,M,26-35,0,C,2,1,19,NaN,NaN,61
550058,1006024,P00372445,M,26-35,12,A,0,1,20,NaN,NaN,121
550059,1006025,P00370853,F,26-35,1,B,1,0,19,NaN,NaN,48
550060,1006026,P00371644,M,36-45,6,C,1,1,20,NaN,NaN,494
550061,1006029,P00372445,F,26-35,1,C,1,1,20,NaN,NaN,599
550062,1006032,P00372445,M,46-50,7,A,3,0,20,NaN,NaN,473
550063,1006033,P00372445,M,51-55,13,B,1,1,20,NaN,NaN,368
550064,1006035,P00375436,F,26-35,1,C,3,0,20,NaN,NaN,371
550065,1006036,P00375436,F,26-35,15,B,4+,1,20,NaN,NaN,137
550066,1006038,P00375436,F,55+,1,C,2,0,20,NaN,NaN,365
550067,1006039,P00371644,F,46-50,0,B,4+,1,20,NaN,NaN,490

In [3]:
bftest['Purchase'] = 0
bftest

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000004,P00128942,M,46-50,7,B,2,1,1,11.0,NaN,0
1,1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN,0
2,1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,NaN,0
3,1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,NaN,0
4,1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0,0
5,1000013,P00350442,M,46-50,1,C,3,1,2,3.0,15.0,0
6,1000013,P00155442,M,46-50,1,C,3,1,1,11.0,15.0,0
7,1000013,P0094542,M,46-50,1,C,3,1,2,4.0,9.0,0
8,1000015,P00161842,M,26-35,7,A,1,0,10,13.0,16.0,0
9,1000022,P00067942,M,18-25,15,A,4+,0,5,14.0,NaN,0
10,1000026,P00046742,M,26-35,7,B,2,1,1,2.0,15.0,0
11,1000026,P00040042,M,26-35,7,B,2,1,5,NaN,NaN,0
12,1000026,P00196542,M,26-35,7,B,2,1,5,8.0,14.0,0
13,1000026,P00004542,M,26-35,7,B,2,1,5,8.0,NaN,0
14,1000028,P00159542,F,26-35,1,C,2,1,10,15.0,16.0,0
15,1000029,P00111542,M,36-45,7,C,1,0,2,17.0,NaN,0
16,1000033,P00121042,M,46-50,3,A,1,1,15,NaN,NaN,0
17,1000033,P00344442,M,46-50,3,A,1,1,5,8.0,14.0,0
18,1000034,P00265242,F,18-25,0,A,0,0,5,8.0,NaN,0
19,1000035,P0096642,M,46-50,1,C,4+,1,2,3.0,4.0,0
20,1000036,P00303042,M,26-35,3,B,0,0,5,NaN,NaN,0
21,1000036,P00059642,M,26-35,3,B,0,0,1,2.0,3.0,0
22,1000042,P00030842,M,26-35,8,C,0,1,1,2.0,15.0,0
23,1000045,P00346442,F,46-50,16,A,1,1,1,2.0,14.0,0
24,1000045,P00357242,F,46-50,16,A,1,1,5,NaN,NaN,0
25,1000045,P00284742,F,46-50,16,A,1,1,5,12.0,NaN,0
26,1000048,P00110842,M,26-35,4,B,3,1,1,2.0,5.0,0
27,1000048,P00251642,M,26-35,4,B,3,1,1,2.0,4.0,0
28,1000053,P00136742,M,26-35,0,B,1,0,1,14.0,16.0,0
29,1000053,P0097342,M,26-35,0,B,1,0,1,15.0,16.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,P00184242,F,26-35,0,B,1,1,9,15.0,NaN,0
233570,1005996,P00045342,F,26-35,0,B,1,1,1,5.0,17.0,0
233571,1006001,P00124642,F,26-35,7,A,0,1,16,NaN,NaN,0
233572,1006002,P00121142,M,51-55,0,C,1,1,8,NaN,NaN,0
233573,1006002,P00233542,M,51-55,0,C,1,1,1,15.0,NaN,0
233574,1006002,P00226342,M,51-55,0,C,1,1,11,15.0,NaN,0
233575,1006002,P00284842,M,51-55,0,C,1,1,1,8.0,17.0,0
233576,1006003,P00313342,F,46-50,17,C,1,0,5,NaN,NaN,0
233577,1006010,P00223542,M,36-45,0,C,1,0,1,8.0,17.0,0
233578,1006013,P00020342,F,26-35,20,C,3,0,1,2.0,NaN,0
233579,1006016,P00014842,M,46-50,1,B,1,1,1,2.0,5.0,0
233580,1006016,P00109542,M,46-50,1,B,1,1,8,14.0,17.0,0
233581,1006018,P00071442,M,36-45,1,C,3,0,15,17.0,NaN,0
233582,1006021,P00112542,M,26-35,12,B,2,1,1,11.0,15.0,0
233583,1006021,P00003442,M,26-35,12,B,2,1,4,5.0,8.0,0
233584,1006023,P00262242,M,26-35,0,C,2,1,1,11.0,16.0,0
233585,1006025,P00161142,F,26-35,1,B,1,0,11,NaN,NaN,0
233586,1006026,P00110742,M,36-45,6,C,1,1,1,2.0,8.0,0
233587,1006028,P00162442,M,18-25,4,A,4+,0,1,16.0,NaN,0
233588,1006030,P00129842,M,26-35,17,C,1,1,6,8.0,15.0,0
233589,1006030,P00241442,M,26-35,17,C,1,1,2,15.0,NaN,0
233590,1006032,P00252442,M,46-50,7,A,3,0,8,NaN,NaN,0
233591,1006033,P00127642,M,51-55,13,B,1,1,1,2.0,15.0,0
233592,1006035,P00135742,F,26-35,1,C,3,0,6,8.0,NaN,0
233593,1006036,P00255442,F,26-35,15,B,4+,1,8,NaN,NaN,0
233594,1006036,P00118942,F,26-35,15,B,4+,1,8,NaN,NaN,0
233595,1006036,P00254642,F,26-35,15,B,4+,1,5,8.0,NaN,0
233596,1006036,P00031842,F,26-35,15,B,4+,1,1,5.0,12.0,0
233597,1006037,P00124742,F,46-50,1,C,4+,0,10,16.0,NaN,0
233598,1006039,P00316642,F,46-50,0,B,4+,1,4,5.0,NaN,0

In [4]:
df = pd.concat([bftrain, bftest], axis = 0)
df

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969
5,1000003,P00193542,M,26-35,15,A,3,0,1,2.0,NaN,15227
6,1000004,P00184942,M,46-50,7,B,2,1,1,8.0,17.0,19215
7,1000004,P00346142,M,46-50,7,B,2,1,1,15.0,NaN,15854
8,1000004,P0097242,M,46-50,7,B,2,1,1,16.0,NaN,15686
9,1000005,P00274942,M,26-35,20,A,1,1,8,NaN,NaN,7871
10,1000005,P00251242,M,26-35,20,A,1,1,5,11.0,NaN,5254
11,1000005,P00014542,M,26-35,20,A,1,1,8,NaN,NaN,3957
12,1000005,P00031342,M,26-35,20,A,1,1,8,NaN,NaN,6073
13,1000005,P00145042,M,26-35,20,A,1,1,1,2.0,5.0,15665
14,1000006,P00231342,F,51-55,9,A,1,0,5,8.0,14.0,5378
15,1000006,P00190242,F,51-55,9,A,1,0,4,5.0,NaN,2079
16,1000006,P0096642,F,51-55,9,A,1,0,2,3.0,4.0,13055
17,1000006,P00058442,F,51-55,9,A,1,0,5,14.0,NaN,8851
18,1000007,P00036842,M,36-45,1,B,1,1,1,14.0,16.0,11788
19,1000008,P00249542,M,26-35,12,C,4+,1,1,5.0,15.0,19614
20,1000008,P00220442,M,26-35,12,C,4+,1,5,14.0,NaN,8584
21,1000008,P00156442,M,26-35,12,C,4+,1,8,NaN,NaN,9872
22,1000008,P00213742,M,26-35,12,C,4+,1,8,NaN,NaN,9743
23,1000008,P00214442,M,26-35,12,C,4+,1,8,NaN,NaN,5982
24,1000008,P00303442,M,26-35,12,C,4+,1,1,8.0,14.0,11927
25,1000009,P00135742,M,26-35,17,C,0,0,6,8.0,NaN,16662
26,1000009,P00039942,M,26-35,17,C,0,0,8,NaN,NaN,5887
27,1000009,P00161442,M,26-35,17,C,0,0,5,14.0,NaN,6973
28,1000009,P00078742,M,26-35,17,C,0,0,5,8.0,14.0,5391
29,1000010,P00085942,F,36-45,1,B,4+,1,2,4.0,8.0,16352
...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,P00184242,F,26-35,0,B,1,1,9,15.0,NaN,0
233570,1005996,P00045342,F,26-35,0,B,1,1,1,5.0,17.0,0
233571,1006001,P00124642,F,26-35,7,A,0,1,16,NaN,NaN,0
233572,1006002,P00121142,M,51-55,0,C,1,1,8,NaN,NaN,0
233573,1006002,P00233542,M,51-55,0,C,1,1,1,15.0,NaN,0
233574,1006002,P00226342,M,51-55,0,C,1,1,11,15.0,NaN,0
233575,1006002,P00284842,M,51-55,0,C,1,1,1,8.0,17.0,0
233576,1006003,P00313342,F,46-50,17,C,1,0,5,NaN,NaN,0
233577,1006010,P00223542,M,36-45,0,C,1,0,1,8.0,17.0,0
233578,1006013,P00020342,F,26-35,20,C,3,0,1,2.0,NaN,0
233579,1006016,P00014842,M,46-50,1,B,1,1,1,2.0,5.0,0
233580,1006016,P00109542,M,46-50,1,B,1,1,8,14.0,17.0,0
233581,1006018,P00071442,M,36-45,1,C,3,0,15,17.0,NaN,0
233582,1006021,P00112542,M,26-35,12,B,2,1,1,11.0,15.0,0
233583,1006021,P00003442,M,26-35,12,B,2,1,4,5.0,8.0,0
233584,1006023,P00262242,M,26-35,0,C,2,1,1,11.0,16.0,0
233585,1006025,P00161142,F,26-35,1,B,1,0,11,NaN,NaN,0
233586,1006026,P00110742,M,36-45,6,C,1,1,1,2.0,8.0,0
233587,1006028,P00162442,M,18-25,4,A,4+,0,1,16.0,NaN,0
233588,1006030,P00129842,M,26-35,17,C,1,1,6,8.0,15.0,0
233589,1006030,P00241442,M,26-35,17,C,1,1,2,15.0,NaN,0
233590,1006032,P00252442,M,46-50,7,A,3,0,8,NaN,NaN,0
233591,1006033,P00127642,M,51-55,13,B,1,1,1,2.0,15.0,0
233592,1006035,P00135742,F,26-35,1,C,3,0,6,8.0,NaN,0
233593,1006036,P00255442,F,26-35,15,B,4+,1,8,NaN,NaN,0
233594,1006036,P00118942,F,26-35,15,B,4+,1,8,NaN,NaN,0
233595,1006036,P00254642,F,26-35,15,B,4+,1,5,8.0,NaN,0
233596,1006036,P00031842,F,26-35,15,B,4+,1,1,5.0,12.0,0
233597,1006037,P00124742,F,46-50,1,C,4+,0,10,16.0,NaN,0
233598,1006039,P00316642,F,46-50,0,B,4+,1,4,5.0,NaN,0

Split X & Y: The point here is to combine train and test to apply all the feature engineering to both at the same time.

In [5]:
target = df.Purchase
df.drop(['Purchase'], axis = 1, inplace = True)

Data Cleaning: It consists of the transformation of all categorical data and all numerical data.

In [6]:
df.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
dtype: object

In [7]:
import numpy as np

df = df.applymap(str)
df.dtypes

User_ID                       object
Product_ID                    object
Gender                        object
Age                           object
Occupation                    object
City_Category                 object
Stay_In_Current_City_Years    object
Marital_Status                object
Product_Category_1            object
Product_Category_2            object
Product_Category_3            object
dtype: object

Categorical Data: All the categories are transformed.

In [8]:
for i in ['User_ID', 'Product_ID', 'Gender', 'Occupation', 'City_Category', 'Marital_Status']:
    df[str(i)] = df[str(i)].astype('category')

df.dtypes

User_ID                       category
Product_ID                    category
Gender                        category
Age                             object
Occupation                    category
City_Category                 category
Stay_In_Current_City_Years      object
Marital_Status                category
Product_Category_1              object
Product_Category_2              object
Product_Category_3              object
dtype: object

Numerical Data: All the numbers are transformed.

In [9]:
df.Age.unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [10]:
df.Age.replace(['0-17'], ['15'], inplace = True)
df.Age.replace(['18-25'], ['21'], inplace = True)
df.Age.replace(['26-35'], ['30'], inplace = True)
df.Age.replace(['36-45'], ['41'], inplace = True)
df.Age.replace(['46-50'], ['48'], inplace = True)
df.Age.replace(['51-55'], ['53'], inplace = True)
df.Age.replace(['55+'], ['60'], inplace = True)

df.Age.unique()

array(['15', '60', '30', '48', '53', '41', '21'], dtype=object)

In [11]:
df.Stay_In_Current_City_Years.unique()

array(['2', '4+', '3', '1', '0'], dtype=object)

In [12]:
df.Stay_In_Current_City_Years.replace(['4+'], ['4'], inplace = True)

df.Stay_In_Current_City_Years.unique()

array(['2', '4', '3', '1', '0'], dtype=object)

In [13]:
df.Product_Category_1.unique()

array(['3', '1', '12', '8', '5', '4', '2', '6', '14', '11', '13', '15',
       '7', '16', '18', '10', '17', '9', '20', '19'], dtype=object)

In [14]:
df.Product_Category_2.unique()

array(['nan', '6.0', '14.0', '2.0', '8.0', '15.0', '16.0', '11.0', '5.0',
       '3.0', '4.0', '12.0', '9.0', '10.0', '17.0', '13.0', '7.0', '18.0'],
      dtype=object)

In [15]:
df.Product_Category_2.replace(['nan'], ['-1'], inplace = True)
df.Product_Category_2.unique()

array(['-1', '6.0', '14.0', '2.0', '8.0', '15.0', '16.0', '11.0', '5.0',
       '3.0', '4.0', '12.0', '9.0', '10.0', '17.0', '13.0', '7.0', '18.0'],
      dtype=object)

In [16]:
df.Product_Category_3.unique()

array(['nan', '14.0', '17.0', '5.0', '4.0', '16.0', '15.0', '8.0', '9.0',
       '13.0', '6.0', '12.0', '3.0', '18.0', '11.0', '10.0'], dtype=object)

In [17]:
df.Product_Category_3.replace(['nan'], ['-1'], inplace = True)
df.Product_Category_3.unique()

array(['-1', '14.0', '17.0', '5.0', '4.0', '16.0', '15.0', '8.0', '9.0',
       '13.0', '6.0', '12.0', '3.0', '18.0', '11.0', '10.0'], dtype=object)

In [18]:
for i in ['Age', 'Stay_In_Current_City_Years', 'Product_Category_1', 'Product_Category_2', 'Product_Category_3']:
    df[str(i)] = df[str(i)].astype('float')

df.dtypes

User_ID                       category
Product_ID                    category
Gender                        category
Age                            float64
Occupation                    category
City_Category                 category
Stay_In_Current_City_Years     float64
Marital_Status                category
Product_Category_1             float64
Product_Category_2             float64
Product_Category_3             float64
dtype: object

In [19]:
df.Product_Category_2.replace([-1], [round(df.Product_Category_2.mean())], inplace = True)
df.Product_Category_2.unique()

array([ 6., 14.,  2.,  8., 15., 16., 11.,  5.,  3.,  4., 12.,  9., 10.,
       17., 13.,  7., 18.])

In [20]:
df.Product_Category_3.replace([-1], [round(df.Product_Category_3.mean())], inplace = True)
df.Product_Category_3.unique()

array([ 3., 14., 17.,  5.,  4., 16., 15.,  8.,  9., 13.,  6., 12., 18.,
       11., 10.])

NA Management: The point here is to find a way for every variable to replace NAs by relevant values.

In [21]:
df.isna().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
dtype: int64

Dummification: The point here is to dummify the categorical data.

In [22]:
dummies = pd.get_dummies(df[['Gender', 'City_Category', 'Marital_Status']])
dummies

,Gender_F,Gender_M,City_Category_A,City_Category_B,City_Category_C,Marital_Status_0,Marital_Status_1
0,1,0,1,0,0,1,0
1,1,0,1,0,0,1,0
2,1,0,1,0,0,1,0
3,1,0,1,0,0,1,0
4,0,1,0,0,1,1,0
5,0,1,1,0,0,1,0
6,0,1,0,1,0,0,1
7,0,1,0,1,0,0,1
8,0,1,0,1,0,0,1
9,0,1,1,0,0,0,1
10,0,1,1,0,0,0,1
11,0,1,1,0,0,0,1
12,0,1,1,0,0,0,1
13,0,1,1,0,0,0,1
14,1,0,1,0,0,1,0
15,1,0,1,0,0,1,0
16,1,0,1,0,0,1,0
17,1,0,1,0,0,1,0
18,0,1,0,1,0,0,1
19,0,1,0,0,1,0,1
20,0,1,0,0,1,0,1
21,0,1,0,0,1,0,1
22,0,1,0,0,1,0,1
23,0,1,0,0,1,0,1
24,0,1,0,0,1,0,1
25,0,1,0,0,1,1,0
26,0,1,0,0,1,1,0
27,0,1,0,0,1,1,0
28,0,1,0,0,1,1,0
29,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...
233569,1,0,0,1,0,0,1
233570,1,0,0,1,0,0,1
233571,1,0,1,0,0,0,1
233572,0,1,0,0,1,0,1
233573,0,1,0,0,1,0,1
233574,0,1,0,0,1,0,1
233575,0,1,0,0,1,0,1
233576,1,0,0,0,1,1,0
233577,0,1,0,0,1,1,0
233578,1,0,0,0,1,1,0
233579,0,1,0,1,0,0,1
233580,0,1,0,1,0,0,1
233581,0,1,0,0,1,1,0
233582,0,1,0,1,0,0,1
233583,0,1,0,1,0,0,1
233584,0,1,0,0,1,0,1
233585,1,0,0,1,0,1,0
233586,0,1,0,0,1,0,1
233587,0,1,1,0,0,1,0
233588,0,1,0,0,1,0,1
233589,0,1,0,0,1,0,1
233590,0,1,1,0,0,1,0
233591,0,1,0,1,0,0,1
233592,1,0,0,0,1,1,0
233593,1,0,0,1,0,0,1
233594,1,0,0,1,0,0,1
233595,1,0,0,1,0,0,1
233596,1,0,0,1,0,0,1
233597,1,0,0,0,1,1,0
233598,1,0,0,1,0,0,1

In [23]:
df = pd.concat([df, dummies], axis = 1)

df

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Gender_F,Gender_M,City_Category_A,City_Category_B,City_Category_C,Marital_Status_0,Marital_Status_1
0,1000001,P00069042,F,15.0,10,A,2.0,0,3.0,6.0,3.0,1,0,1,0,0,1,0
1,1000001,P00248942,F,15.0,10,A,2.0,0,1.0,6.0,14.0,1,0,1,0,0,1,0
2,1000001,P00087842,F,15.0,10,A,2.0,0,12.0,6.0,3.0,1,0,1,0,0,1,0
3,1000001,P00085442,F,15.0,10,A,2.0,0,12.0,14.0,3.0,1,0,1,0,0,1,0
4,1000002,P00285442,M,60.0,16,C,4.0,0,8.0,6.0,3.0,0,1,0,0,1,1,0
5,1000003,P00193542,M,30.0,15,A,3.0,0,1.0,2.0,3.0,0,1,1,0,0,1,0
6,1000004,P00184942,M,48.0,7,B,2.0,1,1.0,8.0,17.0,0,1,0,1,0,0,1
7,1000004,P00346142,M,48.0,7,B,2.0,1,1.0,15.0,3.0,0,1,0,1,0,0,1
8,1000004,P0097242,M,48.0,7,B,2.0,1,1.0,16.0,3.0,0,1,0,1,0,0,1
9,1000005,P00274942,M,30.0,20,A,1.0,1,8.0,6.0,3.0,0,1,1,0,0,0,1
10,1000005,P00251242,M,30.0,20,A,1.0,1,5.0,11.0,3.0,0,1,1,0,0,0,1
11,1000005,P00014542,M,30.0,20,A,1.0,1,8.0,6.0,3.0,0,1,1,0,0,0,1
12,1000005,P00031342,M,30.0,20,A,1.0,1,8.0,6.0,3.0,0,1,1,0,0,0,1
13,1000005,P00145042,M,30.0,20,A,1.0,1,1.0,2.0,5.0,0,1,1,0,0,0,1
14,1000006,P00231342,F,53.0,9,A,1.0,0,5.0,8.0,14.0,1,0,1,0,0,1,0
15,1000006,P00190242,F,53.0,9,A,1.0,0,4.0,5.0,3.0,1,0,1,0,0,1,0
16,1000006,P0096642,F,53.0,9,A,1.0,0,2.0,3.0,4.0,1,0,1,0,0,1,0
17,1000006,P00058442,F,53.0,9,A,1.0,0,5.0,14.0,3.0,1,0,1,0,0,1,0
18,1000007,P00036842,M,41.0,1,B,1.0,1,1.0,14.0,16.0,0,1,0,1,0,0,1
19,1000008,P00249542,M,30.0,12,C,4.0,1,1.0,5.0,15.0,0,1,0,0,1,0,1
20,1000008,P00220442,M,30.0,12,C,4.0,1,5.0,14.0,3.0,0,1,0,0,1,0,1
21,1000008,P00156442,M,30.0,12,C,4.0,1,8.0,6.0,3.0,0,1,0,0,1,0,1
22,1000008,P00213742,M,30.0,12,C,4.0,1,8.0,6.0,3.0,0,1,0,0,1,0,1
23,1000008,P00214442,M,30.0,12,C,4.0,1,8.0,6.0,3.0,0,1,0,0,1,0,1
24,1000008,P00303442,M,30.0,12,C,4.0,1,1.0,8.0,14.0,0,1,0,0,1,0,1
25,1000009,P00135742,M,30.0,17,C,0.0,0,6.0,8.0,3.0,0,1,0,0,1,1,0
26,1000009,P00039942,M,30.0,17,C,0.0,0,8.0,6.0,3.0,0,1,0,0,1,1,0
27,1000009,P00161442,M,30.0,17,C,0.0,0,5.0,14.0,3.0,0,1,0,0,1,1,0
28,1000009,P00078742,M,30.0,17,C,0.0,0,5.0,8.0,14.0,0,1,0,0,1,1,0
29,1000010,P00085942,F,41.0,1,B,4.0,1,2.0,4.0,8.0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,P00184242,F,30.0,0,B,1.0,1,9.0,15.0,3.0,1,0,0,1,0,0,1
233570,1005996,P00045342,F,30.0,0,B,1.0,1,1.0,5.0,17.0,1,0,0,1,0,0,1
233571,1006001,P00124642,F,30.0,7,A,0.0,1,16.0,6.0,3.0,1,0,1,0,0,0,1
233572,1006002,P00121142,M,53.0,0,C,1.0,1,8.0,6.0,3.0,0,1,0,0,1,0,1
233573,1006002,P00233542,M,53.0,0,C,1.0,1,1.0,15.0,3.0,0,1,0,0,1,0,1
233574,1006002,P00226342,M,53.0,0,C,1.0,1,11.0,15.0,3.0,0,1,0,0,1,0,1
233575,1006002,P00284842,M,53.0,0,C,1.0,1,1.0,8.0,17.0,0,1,0,0,1,0,1
233576,1006003,P00313342,F,48.0,17,C,1.0,0,5.0,6.0,3.0,1,0,0,0,1,1,0
233577,1006010,P00223542,M,41.0,0,C,1.0,0,1.0,8.0,17.0,0,1,0,0,1,1,0
233578,1006013,P00020342,F,30.0,20,C,3.0,0,1.0,2.0,3.0,1,0,0,0,1,1,0
233579,1006016,P00014842,M,48.0,1,B,1.0,1,1.0,2.0,5.0,0,1,0,1,0,0,1
233580,1006016,P00109542,M,48.0,1,B,1.0,1,8.0,14.0,17.0,0,1,0,1,0,0,1
233581,1006018,P00071442,M,41.0,1,C,3.0,0,15.0,17.0,3.0,0,1,0,0,1,1,0
233582,1006021,P00112542,M,30.0,12,B,2.0,1,1.0,11.0,15.0,0,1,0,1,0,0,1
233583,1006021,P00003442,M,30.0,12,B,2.0,1,4.0,5.0,8.0,0,1,0,1,0,0,1
233584,1006023,P00262242,M,30.0,0,C,2.0,1,1.0,11.0,16.0,0,1,0,0,1,0,1
233585,1006025,P00161142,F,30.0,1,B,1.0,0,11.0,6.0,3.0,1,0,0,1,0,1,0
233586,1006026,P00110742,M,41.0,6,C,1.0,1,1.0,2.0,8.0,0,1,0,0,1,0,1
233587,1006028,P00162442,M,21.0,4,A,4.0,0,1.0,16.0,3.0,0,1,1,0,0,1,0
233588,1006030,P00129842,M,30.0,17,C,1.0,1,6.0,8.0,15.0,0,1,0,0,1,0,1
233589,1006030,P00241442,M,30.0,17,C,1.0,1,2.0,15.0,3.0,0,1,0,0,1,0,1
233590,1006032,P00252442,M,48.0,7,A,3.0,0,8.0,6.0,3.0,0,1,1,0,0,1,0
233591,1006033,P00127642,M,53.0,13,B,1.0,1,1.0,2.0,15.0,0,1,0,1,0,0,1
233592,1006035,P00135742,F,30.0,1,C,3.0,0,6.0,8.0,3.0,1,0,0,0,1,1,0
233593,1006036,P00255442,F,30.0,15,B,4.0,1,8.0,6.0,3.0,1,0,0,1,0,0,1
233594,1006036,P00118942,F,30.0,15,B,4.0,1,8.0,6.0,3.0,1,0,0,1,0,0,1
233595,1006036,P00254642,F,30.0,15,B,4.0,1,5.0,8.0,3.0,1,0,0,1,0,0,1
233596,1006036,P00031842,F,30.0,15,B,4.0,1,1.0,5.0,12.0,1,0,0,1,0,0,1
233597,1006037,P00124742,F,48.0,1,C,4.0,0,10.0,16.0,3.0,1,0,0,0,1,1,0
233598,1006039,P00316642,F,48.0,0,B,4.0,1,4.0,5.0,3.0,1,0,0,1,0,0,1

In [24]:
df = df.drop(columns = ['Gender', 'City_Category', 'Marital_Status'])

df

,User_ID,Product_ID,Age,Occupation,Stay_In_Current_City_Years,Product_Category_1,Product_Category_2,Product_Category_3,Gender_F,Gender_M,City_Category_A,City_Category_B,City_Category_C,Marital_Status_0,Marital_Status_1
0,1000001,P00069042,15.0,10,2.0,3.0,6.0,3.0,1,0,1,0,0,1,0
1,1000001,P00248942,15.0,10,2.0,1.0,6.0,14.0,1,0,1,0,0,1,0
2,1000001,P00087842,15.0,10,2.0,12.0,6.0,3.0,1,0,1,0,0,1,0
3,1000001,P00085442,15.0,10,2.0,12.0,14.0,3.0,1,0,1,0,0,1,0
4,1000002,P00285442,60.0,16,4.0,8.0,6.0,3.0,0,1,0,0,1,1,0
5,1000003,P00193542,30.0,15,3.0,1.0,2.0,3.0,0,1,1,0,0,1,0
6,1000004,P00184942,48.0,7,2.0,1.0,8.0,17.0,0,1,0,1,0,0,1
7,1000004,P00346142,48.0,7,2.0,1.0,15.0,3.0,0,1,0,1,0,0,1
8,1000004,P0097242,48.0,7,2.0,1.0,16.0,3.0,0,1,0,1,0,0,1
9,1000005,P00274942,30.0,20,1.0,8.0,6.0,3.0,0,1,1,0,0,0,1
10,1000005,P00251242,30.0,20,1.0,5.0,11.0,3.0,0,1,1,0,0,0,1
11,1000005,P00014542,30.0,20,1.0,8.0,6.0,3.0,0,1,1,0,0,0,1
12,1000005,P00031342,30.0,20,1.0,8.0,6.0,3.0,0,1,1,0,0,0,1
13,1000005,P00145042,30.0,20,1.0,1.0,2.0,5.0,0,1,1,0,0,0,1
14,1000006,P00231342,53.0,9,1.0,5.0,8.0,14.0,1,0,1,0,0,1,0
15,1000006,P00190242,53.0,9,1.0,4.0,5.0,3.0,1,0,1,0,0,1,0
16,1000006,P0096642,53.0,9,1.0,2.0,3.0,4.0,1,0,1,0,0,1,0
17,1000006,P00058442,53.0,9,1.0,5.0,14.0,3.0,1,0,1,0,0,1,0
18,1000007,P00036842,41.0,1,1.0,1.0,14.0,16.0,0,1,0,1,0,0,1
19,1000008,P00249542,30.0,12,4.0,1.0,5.0,15.0,0,1,0,0,1,0,1
20,1000008,P00220442,30.0,12,4.0,5.0,14.0,3.0,0,1,0,0,1,0,1
21,1000008,P00156442,30.0,12,4.0,8.0,6.0,3.0,0,1,0,0,1,0,1
22,1000008,P00213742,30.0,12,4.0,8.0,6.0,3.0,0,1,0,0,1,0,1
23,1000008,P00214442,30.0,12,4.0,8.0,6.0,3.0,0,1,0,0,1,0,1
24,1000008,P00303442,30.0,12,4.0,1.0,8.0,14.0,0,1,0,0,1,0,1
25,1000009,P00135742,30.0,17,0.0,6.0,8.0,3.0,0,1,0,0,1,1,0
26,1000009,P00039942,30.0,17,0.0,8.0,6.0,3.0,0,1,0,0,1,1,0
27,1000009,P00161442,30.0,17,0.0,5.0,14.0,3.0,0,1,0,0,1,1,0
28,1000009,P00078742,30.0,17,0.0,5.0,8.0,14.0,0,1,0,0,1,1,0
29,1000010,P00085942,41.0,1,4.0,2.0,4.0,8.0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,P00184242,30.0,0,1.0,9.0,15.0,3.0,1,0,0,1,0,0,1
233570,1005996,P00045342,30.0,0,1.0,1.0,5.0,17.0,1,0,0,1,0,0,1
233571,1006001,P00124642,30.0,7,0.0,16.0,6.0,3.0,1,0,1,0,0,0,1
233572,1006002,P00121142,53.0,0,1.0,8.0,6.0,3.0,0,1,0,0,1,0,1
233573,1006002,P00233542,53.0,0,1.0,1.0,15.0,3.0,0,1,0,0,1,0,1
233574,1006002,P00226342,53.0,0,1.0,11.0,15.0,3.0,0,1,0,0,1,0,1
233575,1006002,P00284842,53.0,0,1.0,1.0,8.0,17.0,0,1,0,0,1,0,1
233576,1006003,P00313342,48.0,17,1.0,5.0,6.0,3.0,1,0,0,0,1,1,0
233577,1006010,P00223542,41.0,0,1.0,1.0,8.0,17.0,0,1,0,0,1,1,0
233578,1006013,P00020342,30.0,20,3.0,1.0,2.0,3.0,1,0,0,0,1,1,0
233579,1006016,P00014842,48.0,1,1.0,1.0,2.0,5.0,0,1,0,1,0,0,1
233580,1006016,P00109542,48.0,1,1.0,8.0,14.0,17.0,0,1,0,1,0,0,1
233581,1006018,P00071442,41.0,1,3.0,15.0,17.0,3.0,0,1,0,0,1,1,0
233582,1006021,P00112542,30.0,12,2.0,1.0,11.0,15.0,0,1,0,1,0,0,1
233583,1006021,P00003442,30.0,12,2.0,4.0,5.0,8.0,0,1,0,1,0,0,1
233584,1006023,P00262242,30.0,0,2.0,1.0,11.0,16.0,0,1,0,0,1,0,1
233585,1006025,P00161142,30.0,1,1.0,11.0,6.0,3.0,1,0,0,1,0,1,0
233586,1006026,P00110742,41.0,6,1.0,1.0,2.0,8.0,0,1,0,0,1,0,1
233587,1006028,P00162442,21.0,4,4.0,1.0,16.0,3.0,0,1,1,0,0,1,0
233588,1006030,P00129842,30.0,17,1.0,6.0,8.0,15.0,0,1,0,0,1,0,1
233589,1006030,P00241442,30.0,17,1.0,2.0,15.0,3.0,0,1,0,0,1,0,1
233590,1006032,P00252442,48.0,7,3.0,8.0,6.0,3.0,0,1,1,0,0,1,0
233591,1006033,P00127642,53.0,13,1.0,1.0,2.0,15.0,0,1,0,1,0,0,1
233592,1006035,P00135742,30.0,1,3.0,6.0,8.0,3.0,1,0,0,0,1,1,0
233593,1006036,P00255442,30.0,15,4.0,8.0,6.0,3.0,1,0,0,1,0,0,1
233594,1006036,P00118942,30.0,15,4.0,8.0,6.0,3.0,1,0,0,1,0,0,1
233595,1006036,P00254642,30.0,15,4.0,5.0,8.0,3.0,1,0,0,1,0,0,1
233596,1006036,P00031842,30.0,15,4.0,1.0,5.0,12.0,1,0,0,1,0,0,1
233597,1006037,P00124742,48.0,1,4.0,10.0,16.0,3.0,1,0,0,0,1,1,0
233598,1006039,P00316642,48.0,0,4.0,4.0,5.0,3.0,1,0,0,1,0,0,1

SPLIT TRAIN TEST

In [26]:
full = pd.concat([df, target], axis = 1)
full.dtypes

User_ID                       category
Product_ID                    category
Age                            float64
Occupation                    category
Stay_In_Current_City_Years     float64
Product_Category_1             float64
Product_Category_2             float64
Product_Category_3             float64
Gender_F                         uint8
Gender_M                         uint8
City_Category_A                  uint8
City_Category_B                  uint8
City_Category_C                  uint8
Marital_Status_0                 uint8
Marital_Status_1                 uint8
Purchase                         int64
dtype: object

In [27]:
full2 = full.drop(columns = ['User_ID', 'Product_ID', 'Occupation'])

In [28]:
train = full2.loc[full2.Purchase != 0,:]
test = full2.loc[full2.Purchase == 0,:]

In [29]:
x_train = train.drop(columns = ['Purchase'])
y_train = train.Purchase

x_test = test.drop(columns = ['Purchase'])

MODEL 1: XGBOOST REGRESSOR

In [30]:
import xgboost

model = xgboost.XGBRegressor(colsample_bytree=0.4,
                 gamma=0,                 
                 learning_rate=0.07,
                 max_depth=3,
                 min_child_weight=1.5,
                 n_estimators=10000,                                                                    
                 reg_alpha=0.75,
                 reg_lambda=0.45,
                 subsample=0.6,
                 seed=42)

In [31]:
x_train.dtypes

Age                           float64
Stay_In_Current_City_Years    float64
Product_Category_1            float64
Product_Category_2            float64
Product_Category_3            float64
Gender_F                        uint8
Gender_M                        uint8
City_Category_A                 uint8
City_Category_B                 uint8
City_Category_C                 uint8
Marital_Status_0                uint8
Marital_Status_1                uint8
dtype: object

In [32]:
model.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.4, gamma=0, learning_rate=0.07, max_delta_step=0,
       max_depth=3, min_child_weight=1.5, missing=None, n_estimators=10000,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0.75, reg_lambda=0.45, scale_pos_weight=1, seed=42,
       silent=True, subsample=0.6)

In [33]:
predictions = model.predict(x_test)

In [34]:
predictions = pd.DataFrame(predictions)
predictions

solution = pd.concat([bftest[['User_ID', 'Product_ID']], predictions], axis = 1)
solution.columns = ['User_ID', 'Product_ID', 'Purchase'

        User_ID Product_ID      Purchase
0       1000004  P00128942  14001.071289
1       1000009  P00113442  10806.439453
2       1000010  P00288442   6656.626465
3       1000010  P00145342   2774.678711
4       1000011  P00053842   2920.751953
5       1000013  P00350442  12447.740234
6       1000013  P00155442  13983.873047
7       1000013   P0094542  11088.329102
8       1000015  P00161842  18447.685547
9       1000022  P00067942   5933.007324
10      1000026  P00046742  12911.300781
11      1000026  P00040042   5847.870117
12      1000026  P00196542   5940.375488
13      1000026  P00004542   6275.953125
14      1000028  P00159542  18194.583984
15      1000029  P00111542  14055.904297
16      1000033  P00121042  14810.869141
17      1000033  P00344442   5830.546387
18      1000034  P00265242   6179.164551
19      1000035   P0096642  10509.886719
20      1000036  P00303042   6080.291504
21      1000036  P00059642  14064.647461
22      1000042  P00030842  13321.337891
23      1000045  P00346442  14303.083984
24      1000045  P00357242   6047.292969
25      1000045  P00284742   6173.573242
26      1000048  P00110842  13150.721680
27      1000048  P00251642   7062.306152
28      1000053  P00136742  13339.873047
29      1000053   P0097342  14439.091797
...         ...        ...           ...
233569  1005996  P00184242  15271.734375
233570  1005996  P00045342  12539.398438
233571  1006001  P00124642  14488.008789
233572  1006002  P00121142   7841.846191
233573  1006002  P00233542  13197.441406
233574  1006002  P00226342   4687.321289
233575  1006002  P00284842  16047.606445
233576  1006003  P00313342   6366.624023
233577  1006010  P00223542  16175.858398
233578  1006013  P00020342  14491.852539
233579  1006016  P00014842  14021.839844
233580  1006016  P00109542   8057.393066
233581  1006018  P00071442  19218.050781
233582  1006021  P00112542  13029.652344
233583  1006021  P00003442   2542.008301
233584  1006023  P00262242  13418.227539
233585  1006025  P00161142   4757.382812
233586  1006026  P00110742  15480.240234
233587  1006028  P00162442  13043.296875
233588  1006030  P00129842  15356.734375
233589  1006030  P00241442  10559.714844
233590  1006032  P00252442   7223.833008
233591  1006033  P00127642  13432.770508
233592  1006035  P00135742  15955.317383
233593  1006036  P00255442   7657.383789
233594  1006036  P00118942   7657.383789
233595  1006036  P00254642   6722.623535
233596  1006036  P00031842  13043.602539
233597  1006037  P00124742  19985.195312
233598  1006039  P00316642   2567.303955

[233599 rows x 3 columns]

In [35]:
solution.to_csv('Solution1.csv', index = False)

TEST ON TRAIN BEFORE FINAL TEST

In [37]:
from sklearn.model_selection import train_test_split
np.random.seed(123)
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size = 0.2)

In [38]:
model.fit(x_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.4, gamma=0, learning_rate=0.07, max_delta_step=0,
       max_depth=3, min_child_weight=1.5, missing=None, n_estimators=10000,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0.75, reg_lambda=0.45, scale_pos_weight=1, seed=42,
       silent=True, subsample=0.6)

In [39]:
y_pred = model.predict(x_test)

In [41]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

In [42]:
rmse

2916.9108556794476